<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Porta.Core\Porta.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Makaretu.Dns" />
    <PackageReference Include="Makaretu.Dns.Multicast" />
  </ItemGroup>

</Project>
